services:
  postgres-auth:
    image: postgres:17
    container_name: postgres-auth
    restart: always
    networks:
      - auth-db
    secrets:
      - auth_db_password
    env_file:
      - ../../services/auth/.env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/auth_db_password
  postgres-id:
    image: postgres:17
    container_name: postgres-id
    restart: always
    networks:
      - id-db
    secrets:
      - id_db_password
    env_file:
      - ../../services/id/.env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/id_db_password
  postgres-log:
    image: postgres:17
    container_name: postgres-log
    restart: always
    networks:
      - log-db
    secrets:
      - log_db_password
    env_file:
      - ../../services/log/.env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/log_db_password
  postgres-notification:
    image: postgres:17
    container_name: postgres-notification
    restart: always
    networks:
      - notification-db
    secrets:
      - notification_db_password
    env_file:
      - ../../services/notification/.env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/notification_db_password
  postgres-content:
    image: postgres:17
    container_name: postgres-content
    restart: always
    networks:
      - content-db
    secrets:
      - content_db_password
    env_file:
      - ../../services/content/.env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/content_db_password
  postgres-membership:
    image: postgres:17
    container_name: postgres-membership
    restart: always
    networks:
      - membership-db
    secrets:
      - membership_db_password
    env_file:
      - ../../services/membership/.env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/membership_db_password
  postgres-community:
    image: postgres:17
    container_name: postgres-community
    restart: always
    networks:
      - community-db
    secrets:
      - community_db_password
    env_file:
      - ../../services/community/.env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/community_db_password

secrets:
  auth_db_password:
    file: ../../secrets/auth_db_password.txt
  id_db_password:
    file: ../../secrets/id_db_password.txt
  log_db_password:
    file: ../../secrets/log_db_password.txt
  notification_db_password:
    file: ../../secrets/notification_db_password.txt
  content_db_password:
    file: ../../secrets/content_db_password.txt
  membership_db_password:
    file: ../../secrets/membership_db_password.txt
  community_db_password:
    file: ../../secrets/community_db_password.txt

networks:
  auth-db:
    driver: bridge
  id-db:
    driver: bridge
  log-db:
    driver: bridge
  notification-db:
    driver: bridge
  content-db:
    driver: bridge
  membership-db:
    driver: bridge
  community-db:
    driver: bridge