services:
  rustfs:
    image: rustfs
    container_name: rustfs
    build: ../../infrastructure/storage/rustfs
    restart: always
    secrets:
      - rustfs_access_key
      - rustfs_secret_key
    environment:
      RUSTFS_ACCESS_KEY_FILE: /run/secrets/rustfs_access_key
      RUSTFS_SECRET_KEY_FILE: /run/secrets/rustfs_secret_key
      RUSTFS_VOLUMES: /data
      RUSTFS_ADDRESS: ":9000"
      RUSTFS_CONSOLE_ENABLE: "true"
      RUSTFS_CONSOLE_ADDRESS: ":9001"
    volumes:
      - rustfs-data:/data
    networks:
      - backend
  rustfs-setup:
    image: rustfs-setup
    container_name: rustfs-setup
    build: ../../infrastructure/storage/setup-rustfs
    restart: "no"
    secrets:
      - rustfs_access_key
      - rustfs_secret_key
      - rustfs_content_access_key
      - rustfs_content_secret_key
      - rustfs_id_access_key
      - rustfs_id_secret_key
      - rustfs_community_access_key
      - rustfs_community_secret_key
    environment:
      RUSTFS_ACCESS_KEY_FILE: /run/secrets/rustfs_access_key
      RUSTFS_SECRET_KEY_FILE: /run/secrets/rustfs_secret_key
      RUSTFS_CONTENT_ACCESS_KEY_FILE: /run/secrets/rustfs_content_access_key
      RUSTFS_CONTENT_SECRET_KEY_FILE: /run/secrets/rustfs_content_secret_key
      RUSTFS_ID_ACCESS_KEY_FILE: /run/secrets/rustfs_id_access_key
      RUSTFS_ID_SECRET_KEY_FILE: /run/secrets/rustfs_id_secret_key
      RUSTFS_COMMUNITY_ACCESS_KEY_FILE: /run/secrets/rustfs_community_access_key
      RUSTFS_COMMUNITY_SECRET_KEY_FILE: /run/secrets/rustfs_community_secret_key
    depends_on:
      rustfs:
        condition: service_started
    networks:
      - backend

secrets:
  rustfs_access_key:
    file: ../../secrets/rustfs_access_key.txt
  rustfs_secret_key:
    file: ../../secrets/rustfs_secret_key.txt
  rustfs_content_access_key:
    file: ../../secrets/rustfs_content_access_key.txt
  rustfs_content_secret_key:
    file: ../../secrets/rustfs_content_secret_key.txt
  rustfs_id_access_key:
    file: ../../secrets/rustfs_id_access_key.txt
  rustfs_id_secret_key:
    file: ../../secrets/rustfs_id_secret_key.txt
  rustfs_community_access_key:
    file: ../../secrets/rustfs_community_access_key.txt
  rustfs_community_secret_key:
    file: ../../secrets/rustfs_community_secret_key.txt