services:
  auth:
    image: auth
    container_name: auth
    build: ../../services/auth
    restart: always
    networks:
      - backend
      - auth-db
    secrets:
      - auth_db_password
      - auth_jwt_secret
    env_file:
      - ../../services/auth/.env
      - ../../services/auth/.env.jwt
    environment:
      JWT_SECRET_KEY: /run/secrets/auth_jwt_secret
      DB_PASSWORD_FILE: /run/secrets/auth_db_password
  log:
    image: log
    container_name: log
    build: ../../services/log
    restart: always
    networks:
      - backend
      - log-db
    secrets:
      - log_db_password
    env_file:
      - ../../services/log/.env
    environment:
      DB_PASSWORD_FILE: /run/secrets/log_db_password
  notification:
    image: notification
    container_name: notification
    build: ../../services/notification
    restart: always
    networks:
      - backend
      - notification-db
    secrets:
      - notification_db_password
    env_file:
      - ../../services/notification/.env
    environment:
      DB_PASSWORD_FILE: /run/secrets/notification_db_password
  content:
    image: content
    container_name: content
    build: ../../services/content
    restart: always
    networks:
      - backend
      - content-db
    secrets:
      - content_db_password
    env_file:
      - ../../services/content/.env
    environment:
      DB_PASSWORD_FILE: /run/secrets/content_db_password
  membership:
    image: membership
    container_name: membership
    build: ../../services/membership
    restart: always
    networks:
      - backend
      - membership-db
    secrets:
      - membership_db_password
    env_file:
      - ../../services/membership/.env
    environment:
      DB_PASSWORD_FILE: /run/secrets/membership_db_password
  community:
    image: community
    container_name: community
    build: ../../services/community
    restart: always
    networks:
      - backend
      - community-db
    secrets:
      - community_db_password
    env_file:
      - ../../services/community/.env
    environment:
      DB_PASSWORD_FILE: /run/secrets/community_db_password
  id:
    image: id
    container_name: id
    build: ../../services/id
    restart: always
    networks:
      - backend
      - id-db
    secrets:
      - id_db_password
    env_file:
      - ../../services/id/.env
    environment:
      DB_PASSWORD_FILE: /run/secrets/id_db_password
  middleware:
    image: middleware
    container_name: middleware
    build: ../../services/middleware
    restart: always
    networks:
      - backend
    secrets:
      - auth_jwt_secret
    env_file:
      - ../../services/auth/.env.jwt
    environment:
      JWT_SECRET_KEY: /run/secrets/auth_jwt_secret

secrets:
  auth_db_password:
    file: ../../secrets/auth_db_password.txt
  auth_jwt_secret:
    file: ../../secrets/auth_jwt_secret.txt
  log_db_password:
    file: ../../secrets/log_db_password.txt
  notification_db_password:
    file: ../../secrets/notification_db_password.txt
  content_db_password:
    file: ../../secrets/content_db_password.txt
  membership_db_password:
    file: ../../secrets/membership_db_password.txt
  community_db_password:
    file: ../../secrets/community_db_password.txt
  id_db_password:
    file: ../../secrets/id_db_password.txt
