services:
  gateway:
    image: gateway
    container_name: gateway
    build: ../../infrastructure/gateway
    restart: always
    networks:
      # - frontend
      - backend
      - monitoring
      - logging
    ports:
      - '3443:443'
      - '3080:80'
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    depends_on:
      # frontend:
      #   condition: service_started
      auth:
        condition: service_started
      id:
        condition: service_started
      log:
        condition: service_started
      notification:
        condition: service_started
      content:
        condition: service_started
      membership:
        condition: service_started
      community:
        condition: service_started
      kibana:
        condition: service_started
        required: false
      grafana:
        condition: service_started
        required: false