services:
  nginx:
    image: nginx
    container_name: nginx
    build: ../../gateway/nginx
    restart: always
    networks:
      - frontend
      - backend
      - monitoring
    ports:
      - '443:443'
      - '80:80'
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}