name: cms

include:
  - ./stacks/compose.services.yml
  - ./stacks/compose.gateway.yml
  - ./stacks/compose.databases.yml
  - ./stacks/compose.monitoring.yml
  - ./stacks/compose.logging.yml

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  monitoring:
    driver: bridge
  logging:
    driver: bridge