name: cms

include:
  - ./stacks/compose.auth.yml
  - ./stacks/compose.gateway.yml
  - ./stacks/compose.databases.yml
  - ./stacks/compose.monitoring.yml

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  monitoring:
    driver: bridge
  auth-db:
    driver: bridge