{
 "title": "container_dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Containers Monitored",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (name) (container_last_seen{image!=\"\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{image!=\"\"}[2m])) + sum(rate(container_fs_writes_bytes_total{image!=\"\"}[2m]))",
     "legendFormat": "Total Disk I/O"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{image!=\"\"}[2m])) + sum(rate(container_network_transmit_bytes_total{image!=\"\"}[2m]))",
     "legendFormat": "Total Network I/O"
    }
   ]
  },
  {
   "title": "CPU Usage by Container",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=~\".*docker.*\", name!=\"\"}[2m])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RAM Usage by Container",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{id=~\".*docker.*\", name!=\"\"}) by (name) / (16 * 1024 * 1024 * 1024)) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}