events {}

http
{
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    server
    {
        listen 80;
        server_name localhost api.localhost ops.localhost;

            return 301 https://$host$request_uri;
    }

    server
    {
        listen 443 ssl;
        server_name localhost;

        include /etc/nginx/ssl.conf;

        location /
        {
            include /etc/nginx/proxy.conf;
            proxy_pass http://frontend:8000/;
        }
    }

    server
    {
        listen 443 ssl;
        server_name api.localhost;

        include /etc/nginx/ssl.conf;

        error_page 404 /404.html;

        location /auth/
        {
            include /etc/nginx/proxy.conf;
            proxy_pass http://auth:8000/;
        }

        location /id/
        {
            include /etc/nginx/proxy.conf;
            proxy_pass http://id:8000/;
        }

        location /community/
        {
            include /etc/nginx/proxy.conf;
            proxy_pass http://community:8000/;
        }

        location /content/
        {
            include /etc/nginx/proxy.conf;
            proxy_pass http://content:8000/;
        }

        location /membership/
        {
            include /etc/nginx/proxy.conf;
            proxy_pass http://membership:8000/;
        }

        location /notification/
        {
            include /etc/nginx/proxy.conf;
            proxy_pass http://notification:8000/;
        }

        location /log/
        {
            include /etc/nginx/proxy.conf;
            proxy_pass http://log:8000/;
        }

        location /
        {
            return 404;
        }
        
        location /404.html
        {
            root /usr/share/nginx/html;
            internal;
        }
    }

    #server
    #{
    #    listen 443 ssl;
    #    server_name ops.localhost;
    #
    #    include /etc/nginx/ssl.conf;
    #
    #    location /monitor
    #    {
    #        include /etc/nginx/proxy.conf;
    #        proxy_pass http://grafana:3000;
    #    }
    #
    #    location /logs
    #    {
    #        include /etc/nginx/proxy.conf;
    #        proxy_pass http://kibana:5601;
    #    }
    #
    #    location /alerts
    #    {
    #        return 200 'AlertManager Service';
    #        add_header Content-Type text/plain;
    #    }
    #
    #    location /
    #    {
    #        return 302 /monitor/;
    #    }
    #}
}
