events {}

http
{
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    server
    {
        listen 80;
        server_name localhost api.localhost ops.localhost;

            return 301 https://$host$request_uri;
    }

    server
    {
        listen 443 ssl;
        server_name localhost;

        include /etc/nginx/ssl.conf;

        location /
        {
            return 404;
            # include /etc/nginx/proxy.conf;
            # proxy_pass http://frontend:8000/;
        }
    }

    server
    {
        listen 443 ssl;
        server_name api.localhost;

        include /etc/nginx/ssl.conf;

        error_page 404 /404.html;

        location ^~ /internal/ {
            return 404;
        }

        location /id/createUser
        {
            return 404;
        }

        location /auth/
        {
            include /etc/nginx/proxy.conf;
            proxy_pass http://auth:8000/;
        }

        location /id/
        {
            include /etc/nginx/proxy.conf;
            proxy_pass http://id:3000/;
        }

        location /community/
        {
            include /etc/nginx/proxy.conf;
            proxy_pass http://community:8000/;
        }

        location /content/
        {
            include /etc/nginx/proxy.conf;
            proxy_pass http://content:8000/;
        }

        location /membership/
        {
            include /etc/nginx/proxy.conf;
            proxy_pass http://membership:8000/;
        }

        location /notification/
        {
            include /etc/nginx/proxy.conf;
            proxy_pass http://notification:8000/;
        }

        location /log/
        {
            include /etc/nginx/proxy.conf;
            proxy_pass http://log:8000/;
        }

        location /orchestration/
        {
            include /etc/nginx/proxy.conf;
            proxy_pass http://orchestration:8000/;
        }

        location /
        {
            return 404;
        }
        
        location /404.html
        {
            root /usr/share/nginx/html;
            internal;
        }
    }

    server
    {
        listen 443 ssl;
        server_name ops.localhost;
    
        resolver 127.0.0.11 valid=10s ipv6=off;

        include /etc/nginx/ssl.conf;
    
        location /monitor
        {
            include /etc/nginx/proxy.conf;
            set $grafana_upstream grafana:3000;
            proxy_pass http://$grafana_upstream;
        }
    
        location /logs
        {
            include /etc/nginx/proxy.conf;
            set $kibana_upstream kibana:5601;
            proxy_pass http://$kibana_upstream;
        }
    
        location /alerts
        {
            include /etc/nginx/proxy.conf;
            set $alertmanager_upstream alertmanager:8000;
            proxy_pass http://$alertmanager_upstream;
        }

        location /
        {
            return 404;
        }
        
        location /404.html
        {
            root /usr/share/nginx/html;
            internal;
        }
    }
}
