server.name: kibana
server.host: "0.0.0.0"

server.basePath: "/logs"
server.rewriteBasePath: true

elasticsearch.hosts:
  - ${ELASTICSEARCH_HOSTS}

monitoring.ui.container.elasticsearch.enabled: true
logging.root.level: info

elasticsearch.username: "${KIBANA_USERNAME}"
elasticsearch.password: "${KIBANA_PASSWORD}"