events {}

http
{
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    server
    {
        listen 80;
        server_name localhost.com api.localhost.com ops.localhost.com;

        return 301 https://$host$request_uri;
    }

    server
    {
        listen 443 ssl;
        server_name localhost.com;

        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;
        ssl_protocols TLSv1.2 TLSv1.3;

        location /
        {
            return 200 'Frontend Service';
            add_header Content-Type text/plain;
        }
    }

    server
    {
        listen 443 ssl;
        server_name api.localhost;

        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;
        ssl_protocols TLSv1.2 TLSv1.3;

        location /auth/
        {
            return 200 'Auth Service';
            add_header Content-Type text/plain;
        }

        location /
        {
            return 404;
        }
    }

    server
    {
        listen 443 ssl;
        server_name ops.localhost;

        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;
        ssl_protocols TLSv1.2 TLSv1.3;

        location /monitor/
        {
            return 200 'Grafana Service';
            add_header Content-Type text/plain;
        }

        location /logs/
        {
            return 200 'Kibana Service';
            add_header Content-Type text/plain;
        }

        location /metrics/
        {
            return 200 'Prometheus Service';
            add_header Content-Type text/plain;
        }

        location /alerts/
        {
            return 200 'AlertManager Service';
            add_header Content-Type text/plain;
        }

        location /
        {
            return 302 /monitor/;
        }
    }
}
