input {
  beats {
    port => 5044
  }
}

output {
    elasticsearch {
        hosts => ["${ELASTICSEARCH_HOSTS}"]
        user => "${LOGSTASH_USERNAME}"
        password => "${LOGSTASH_PASSWORD}"
        index => "logs-%{+YYYY.MM.dd}"
    }
}