input {

}

filter {

}

output {
    elasticsearch {
        hosts => ["http://elasticsearch:9200"]

        user => "logstash_writer"

        password => "${LOGSTASH_PASSWORD}"

        index => "logs-%{+YYYY.MM.dd}"
    }
}