smallrye.jwt.verify.secretkey=${JWT_SECRET_KEY}
smallrye.jwt.verify.algorithm=HS256
smallrye.jwt.require.named-principal=false
smallrye.jwt.time-to-live=0
mp.jwt.verify.issuer=NONE
quarkus.http.auth.proactive=false
